--- 
- hosts: dcos-cluster,dcos-bootstrap
  sudo: yes
  roles:
    - common
  tags:
    - common

- hosts: dcos-bootstrap
  sudo: yes
  roles:
    - dcos-bootstrap
  tags:
    - bootstrap
    - bootstrap-node