--- 
- hosts: dcos-cluster,dcos-bootstrap
  sudo: yes
  roles:
    - common
  tags:
    - common

- hosts: dcos-bootstrap
  sudo: yes
  roles:
    - dcos-bootstrap
  tags:
    - bootstrap
    - bootstrap-node

- hosts: mesos-master
  sudo: yes
  roles:
    - bootstrap-mesos-master
  tags:
    - bootstrap
    - bootstrap-mesos-master

- hosts: mesos-agent
  sudo: yes
  roles:
    - bootstrap-mesos-slave
  tags:
    - bootstrap
    - bootstrap-mesos-slave